language: scala
dist: trusty
sudo: false
group: beta
scala:
- 2.12.2
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
notifications:
  slack:
    secure: ltgIyHnWM/apr/VaeX9diKH6o4chcZO+1SUmjTuJIoRJCMdKjv0TY4k+HMabLwe/4ZXhzZ/nq2VhbUZDnvsL90b9MfeDjcvf9ku20MSNuiDvZZC3yYgj7I+x3Y2kbVZcugTPbl2Ig0UGqSGCuVyqYnLSBPQ1LOn/gug3hGMqcJ5vb40g1zRPG842yZjJ5UTo5suitPc63YYuAcddoBnBCqAez+2Z8W4Gf6vu27DonTEcisiu2MmWD2X2AqmahuZi7TE0c3o3CBrrY38N+EPvonuBHSO03vaCF0XvabOxALHzLQDG6byw/u4anGXpa0/dhrT6gglb31y10hzxH6yfb2p9a/LNrY4gKyz4bzEBplTb7uogaJCJpYiQDdINxRGkVdbHRDyuAsEo+Y7y6pW60oEOLUuLmvKSAjPNp5k1o2Mmx13O1SBbAxP6YSiZStptKYko8BlSEIsBSvhXaZuIcoAeMgypcxyemZWi9QBIH+SNgueIdGCTBZ5lQe+nBLhjft+0hFnV9mJMazGmvaue5UGukalLhHgyNhnGdTrC1QVjU53iDY95GY3QJhcdnXr6cCvEAZvHwefjnTLCiKqNAgG77Y3w8CH5vyFwoS/dYFzl08urIxblxL8bUrI5vgNrt38gW/vKHxXZBzj6c80xyfdVGcdex/m/jI5BllLMH3A=
